#!/usr/bin/env bash

OS_NAME=`uname -s | tr A-Z a-z`
if [ "$OS_NAME" = "linux" ]; then
    SDL_I=`sdl3-config --cflags`
    SDL_L=`sdl3-config --libs`
    if [ "$SDL_I" = "" ]; then
        echo "'sdl3-config --cflags' didn't return anything - is SDL3 installed?)"
        exit 1
    fi
    SDL_L="$SDL_L/SDL3"
elif [ "$OS_NAME" = "darwin" ]; then
    BREW=`brew --prefix`
    if [ "$BREW" = "" ]; then
        echo "'brew --prefix' didn't return a path - is Homebrew installed?)"
        exit 1
    fi
    SDL=`brew --prefix sdl3`
    if [ "$SDL" = "" ]; then
        echo "'brew --prefix sdl3' didn't return a path - is SDL3 installed?)"
        exit 1
    fi
    SDL_I="-I$SDL/include"
    SDL_L="-L$SDL/lib"
fi

clang -O2 -Wall -DNORMALUNIX \
  -Ithirdparty/platform \
  -Ithirdparty/LittleMUS \
  -Ithirdparty/Nuked-OPL3 \
  -Ilinuxdoom-1.10 \
  "$SDL_I" \
  "$SDL_L" \
  -lSDL3 \
  linuxdoom-1.10/*.c \
  thirdparty/platform/*.c \
  thirdparty/LittleMUS/*.c \
  thirdparty/Nuked-OPL3/*.c \
  -o doom
